//! Stable error codes exposed to engine adapters.
//!
//! Codes are unique within one operation. Different operations may reuse a
//! numeric value because callers always interpret an error in the context of
//! the operation they submitted.

pub const CREATE_SPACE_PASSPHRASE_MISMATCH_CODE: u32 = 1201;
pub const CREATE_SPACE_ALREADY_INITIALIZED_CODE: u32 = 1202;
pub const CREATE_SPACE_FAILED_CODE: u32 = 1203;
pub const CREATE_SPACE_DEVICE_NAME_REQUIRED_CODE: u32 = 1204;
pub const CREATE_SPACE_ALREADY_SETUP_CODE: u32 = 1205;

pub const UNLOCK_SPACE_SETUP_NOT_COMPLETED_CODE: u32 = 1211;
pub const UNLOCK_SPACE_UNAUTHORIZED_CODE: u32 = 1212;
pub const UNLOCK_SPACE_FAILED_CODE: u32 = 1213;
pub const RECOVER_SESSION_UNAVAILABLE_CODE: u32 = 1214;
pub const UNLOCK_SPACE_NOT_INITIALIZED_CODE: u32 = 1215;
pub const UNLOCK_SPACE_CORRUPTED_CODE: u32 = 1216;
pub const RECOVER_SESSION_RECEIVE_UNAVAILABLE_CODE: u32 = 1217;

pub const JOIN_SPACE_DEVICE_NAME_REQUIRED_CODE: u32 = 1231;
pub const JOIN_SPACE_NOT_SETUP_CODE: u32 = 1232;
pub const JOIN_SPACE_PASSPHRASE_MISMATCH_CODE: u32 = 1233;
pub const JOIN_SPACE_INVITATION_NOT_FOUND_CODE: u32 = 1234;
pub const JOIN_SPACE_SPONSOR_REJECTED_CODE: u32 = 1235;
pub const JOIN_SPACE_SPONSOR_UNREACHABLE_CODE: u32 = 1236;
pub const JOIN_SPACE_TIMEOUT_CODE: u32 = 1237;
pub const JOIN_SPACE_FAILED_CODE: u32 = 1238;
pub const JOIN_SPACE_INVITATION_EXPIRED_CODE: u32 = 1281;
pub const JOIN_SPACE_SPONSOR_DECLINED_CODE: u32 = 1282;
pub const JOIN_SPACE_SERVICE_UNAVAILABLE_CODE: u32 = 1283;
pub const JOIN_SPACE_CONNECTION_LOST_CODE: u32 = 1284;
pub const JOIN_SPACE_SPONSOR_TIMEOUT_CODE: u32 = 1285;
pub const JOIN_SPACE_CORRUPTED_KEY_CODE: u32 = 1286;
pub const JOIN_SPACE_PENDING_MIGRATION_CODE: u32 = 1287;
pub const JOIN_SPACE_NOT_UNLOCKED_CODE: u32 = 1288;
pub const JOIN_SPACE_INVALID_CIPHERTEXT_CODE: u32 = 1289;
pub const JOIN_SPACE_STORAGE_CODE: u32 = 1290;
pub const JOIN_SPACE_SPONSOR_UPGRADE_REQUIRED_CODE: u32 = 1291;
pub const JOIN_SPACE_UNREADABLE_HISTORY_REQUIRES_CONFIRMATION_CODE: u32 = 1292;
pub const JOIN_SPACE_SPONSOR_ADMISSION_UNAVAILABLE_CODE: u32 = 1293;
pub const CANCEL_JOIN_SPACE_NOT_FOUND_CODE: u32 = 1294;
pub const JOIN_SPACE_PREVIOUS_JOIN_CANNOT_BE_SUPERSEDED_CODE: u32 = 1295;

pub const CANCEL_INVITATION_NOT_ISSUED_CODE: u32 = 1301;
pub const CANCEL_INVITATION_FAILED_CODE: u32 = 1302;
pub const CANCEL_INVITATION_UNAVAILABLE_CODE: u32 = 1303;
pub const RESET_SPACE_UNAVAILABLE_CODE: u32 = 1311;
pub const RESET_SPACE_FAILED_CODE: u32 = 1312;
pub const QUERY_SETUP_STATE_UNAVAILABLE_CODE: u32 = 1321;
pub const QUERY_SETUP_STATE_FAILED_CODE: u32 = 1322;
pub const QUERY_MIGRATION_PROGRESS_UNAVAILABLE_CODE: u32 = 1331;
pub const QUERY_MIGRATION_PROGRESS_FAILED_CODE: u32 = 1332;
pub const QUERY_STORAGE_STATS_FAILED_CODE: u32 = 1341;
pub const CLEAR_STORAGE_CACHE_FAILED_CODE: u32 = 1342;
pub const QUERY_LOCAL_DEVICE_FAILED_CODE: u32 = 1351;
pub const QUERY_ENCRYPTION_STATE_FAILED_CODE: u32 = 1361;
pub const LOCK_ENCRYPTION_FAILED_CODE: u32 = 1362;
pub const VERIFY_SECURE_STORAGE_ACCESS_FAILED_CODE: u32 = 1363;
pub const FACTORY_RESET_UNAVAILABLE_CODE: u32 = 1371;
pub const FACTORY_RESET_KEY_MATERIAL_FAILED_CODE: u32 = 1372;
pub const FACTORY_RESET_STORAGE_FAILED_CODE: u32 = 1373;
pub const FACTORY_RESET_FAILED_CODE: u32 = 1374;

pub const MEMBER_INVALID_INPUT_CODE: u32 = 1380;
pub const MEMBER_UNAVAILABLE_CODE: u32 = 1381;
pub const MEMBER_NOT_FOUND_CODE: u32 = 1382;
pub const MEMBER_REPOSITORY_FAILED_CODE: u32 = 1383;
pub const MEMBER_LOCAL_IDENTITY_FAILED_CODE: u32 = 1384;
pub const MEMBER_LEGACY_BOOTSTRAP_FAILED_CODE: u32 = 1389;
pub const SPACE_PROTECTION_FAILED_CODE: u32 = 1391;
pub const MEMBERSHIP_CONFLICT_INVALID_INPUT_CODE: u32 = 1395;
pub const MEMBERSHIP_CONFLICT_LOCKED_CODE: u32 = 1396;
pub const MEMBERSHIP_CONFLICT_INVALID_CHOICE_CODE: u32 = 1397;
pub const MEMBERSHIP_CONFLICT_UNAVAILABLE_CODE: u32 = 1398;
pub const MEMBERSHIP_CONFLICT_RECOVERY_REQUIRED_CODE: u32 = 1399;
pub const MEMBERSHIP_CONFLICT_COMMITTED_PENDING_CODE: u32 = 1400;
pub const QUERY_WORKSPACE_CONVERGENCE_UNAVAILABLE_CODE: u32 = 1392;
pub const QUERY_WORKSPACE_CONVERGENCE_FAILED_CODE: u32 = 1393;
pub const QUERY_WORKSPACE_CONVERGENCE_CORRUPT_CODE: u32 = 1394;
pub const QUERY_PEER_CONNECTIONS_FAILED_CODE: u32 = 1381;
pub const REFRESH_PEER_CONNECTIONS_FAILED_CODE: u32 = 1382;

pub const QUERY_SETTINGS_FAILED_CODE: u32 = 1391;
pub const UPDATE_SETTINGS_FAILED_CODE: u32 = 1392;
pub const PROBE_RELAY_UNAVAILABLE_CODE: u32 = 1393;
pub const QUERY_RELAY_CREDENTIAL_FAILED_CODE: u32 = 1394;
pub const SAVE_RELAY_FAILED_CODE: u32 = 1395;
pub const SEARCH_INVALID_QUERY_CODE: u32 = 1391;
pub const SEARCH_BAD_REQUEST_CODE: u32 = 1392;
pub const SEARCH_SESSION_LOCKED_CODE: u32 = 1393;
pub const SEARCH_INDEX_NOT_READY_CODE: u32 = 1394;
pub const SEARCH_INDEX_REBUILDING_CODE: u32 = 1395;
pub const SEARCH_INDEX_UNAVAILABLE_CODE: u32 = 1396;
pub const SEARCH_SERVICE_UNAVAILABLE_CODE: u32 = 1397;
pub const SEARCH_REBUILD_ALREADY_RUNNING_CODE: u32 = 1398;
pub const SEARCH_FAILED_CODE: u32 = 1399;

pub const HISTORY_INVALID_INPUT_CODE: u32 = 1401;
pub const HISTORY_NOT_FOUND_CODE: u32 = 1402;
pub const HISTORY_UNSUPPORTED_CONTENT_CODE: u32 = 1403;
pub const HISTORY_FAILED_CODE: u32 = 1404;
pub const QUERY_UPGRADE_STATUS_FAILED_CODE: u32 = 1401;
pub const ACKNOWLEDGE_UPGRADE_FAILED_CODE: u32 = 1402;

pub const QUERY_DIAGNOSTICS_FAILED_CODE: u32 = 1411;
pub const UPDATE_DEBUG_MODE_FAILED_CODE: u32 = 1412;
pub const EXPORT_DIAGNOSTIC_LOGS_FAILED_CODE: u32 = 1413;
pub const EXPORT_DIAGNOSTIC_LOGS_INVALID_TARGET_CODE: u32 = 1414;
pub const EXPORT_DIAGNOSTIC_LOGS_UNAUTHORIZED_CODE: u32 = 1415;
pub const EXPORT_DIAGNOSTIC_LOGS_UNAVAILABLE_CODE: u32 = 1416;
pub const RECEIVE_INVALID_INPUT_CODE: u32 = 1411;
pub const RECEIVE_UNAVAILABLE_CODE: u32 = 1412;
pub const RECEIVE_FAILED_CODE: u32 = 1413;
pub const TRANSFER_CANCEL_UNAVAILABLE_CODE: u32 = 1414;
pub const TRANSFER_CANCEL_FAILED_CODE: u32 = 1415;

pub const CAPTURE_CURRENT_CLIPBOARD_FAILED_CODE: u32 = 1421;
pub const QUERY_ACTIVE_CLIPBOARD_FAILED_CODE: u32 = 1422;
pub const EXPORT_CONFIG_FAILED_CODE: u32 = 1421;
pub const PREVIEW_CONFIG_IMPORT_FAILED_CODE: u32 = 1422;
pub const STAGE_CONFIG_IMPORT_FAILED_CODE: u32 = 1423;
pub const CONFIG_FILE_INVALID_HANDLE_CODE: u32 = 1424;
pub const CONFIG_FILE_UNAUTHORIZED_CODE: u32 = 1425;
pub const CONFIG_FILE_UNAVAILABLE_CODE: u32 = 1426;

pub const LIST_MOBILE_DEVICES_FAILED_CODE: u32 = 1431;
pub const REVOKE_MOBILE_DEVICE_FAILED_CODE: u32 = 1432;
pub const AUTHENTICATE_MOBILE_REQUEST_FAILED_CODE: u32 = 1433;
pub const REVALIDATE_MOBILE_CREDENTIAL_FAILED_CODE: u32 = 1434;
pub const REGISTER_MOBILE_DEVICE_FAILED_CODE: u32 = 1435;
pub const UPDATE_MOBILE_DEVICE_FAILED_CODE: u32 = 1436;
pub const QUERY_MOBILE_SYNC_SETTINGS_FAILED_CODE: u32 = 1437;
pub const UPDATE_MOBILE_SYNC_SETTINGS_FAILED_CODE: u32 = 1438;
pub const RESTORE_CLIPBOARD_NOT_FOUND_CODE: u32 = 1431;
pub const RESTORE_CLIPBOARD_UNAVAILABLE_CODE: u32 = 1432;
pub const RESTORE_CLIPBOARD_FAILED_CODE: u32 = 1433;

pub const ENTRY_DELIVERY_NOT_FOUND_CODE: u32 = 1441;
pub const ENTRY_DELIVERY_FAILED_CODE: u32 = 1442;
pub const RESEND_STORAGE_FAILED_CODE: u32 = 1451;
pub const RESEND_DISPATCH_FAILED_CODE: u32 = 1452;
pub const BLOB_NOT_FOUND_CODE: u32 = 1461;
pub const THUMBNAIL_NOT_FOUND_CODE: u32 = 1462;
pub const ENTRY_FILE_NOT_FOUND_CODE: u32 = 1463;
pub const RESOURCE_READ_FAILED_CODE: u32 = 1464;

#[cfg(test)]
mod tests {
    use super::*;

    fn assert_unique(codes: &[u32]) {
        for (index, code) in codes.iter().enumerate() {
            assert!(
                !codes[index + 1..].contains(code),
                "duplicate error code {code}"
            );
        }
    }

    #[test]
    fn codes_are_unique_within_each_operation() {
        for codes in [
            &[
                CREATE_SPACE_PASSPHRASE_MISMATCH_CODE,
                CREATE_SPACE_ALREADY_INITIALIZED_CODE,
                CREATE_SPACE_FAILED_CODE,
                CREATE_SPACE_DEVICE_NAME_REQUIRED_CODE,
                CREATE_SPACE_ALREADY_SETUP_CODE,
            ][..],
            &[
                UNLOCK_SPACE_SETUP_NOT_COMPLETED_CODE,
                UNLOCK_SPACE_UNAUTHORIZED_CODE,
                UNLOCK_SPACE_FAILED_CODE,
                UNLOCK_SPACE_NOT_INITIALIZED_CODE,
                UNLOCK_SPACE_CORRUPTED_CODE,
            ],
            &[
                RECOVER_SESSION_UNAVAILABLE_CODE,
                RECOVER_SESSION_RECEIVE_UNAVAILABLE_CODE,
            ],
            &[
                JOIN_SPACE_DEVICE_NAME_REQUIRED_CODE,
                JOIN_SPACE_NOT_SETUP_CODE,
                JOIN_SPACE_PASSPHRASE_MISMATCH_CODE,
                JOIN_SPACE_INVITATION_NOT_FOUND_CODE,
                JOIN_SPACE_SPONSOR_REJECTED_CODE,
                JOIN_SPACE_SPONSOR_UNREACHABLE_CODE,
                JOIN_SPACE_TIMEOUT_CODE,
                JOIN_SPACE_FAILED_CODE,
                JOIN_SPACE_INVITATION_EXPIRED_CODE,
                JOIN_SPACE_SPONSOR_DECLINED_CODE,
                JOIN_SPACE_SERVICE_UNAVAILABLE_CODE,
                JOIN_SPACE_CONNECTION_LOST_CODE,
                JOIN_SPACE_SPONSOR_TIMEOUT_CODE,
                JOIN_SPACE_CORRUPTED_KEY_CODE,
                JOIN_SPACE_PENDING_MIGRATION_CODE,
                JOIN_SPACE_NOT_UNLOCKED_CODE,
                JOIN_SPACE_INVALID_CIPHERTEXT_CODE,
                JOIN_SPACE_STORAGE_CODE,
                JOIN_SPACE_SPONSOR_UPGRADE_REQUIRED_CODE,
                JOIN_SPACE_UNREADABLE_HISTORY_REQUIRES_CONFIRMATION_CODE,
                JOIN_SPACE_SPONSOR_ADMISSION_UNAVAILABLE_CODE,
                JOIN_SPACE_PREVIOUS_JOIN_CANNOT_BE_SUPERSEDED_CODE,
                CANCEL_JOIN_SPACE_NOT_FOUND_CODE,
            ],
            &[
                MEMBER_INVALID_INPUT_CODE,
                MEMBER_UNAVAILABLE_CODE,
                MEMBER_NOT_FOUND_CODE,
                MEMBER_REPOSITORY_FAILED_CODE,
                MEMBER_LOCAL_IDENTITY_FAILED_CODE,
                MEMBER_LEGACY_BOOTSTRAP_FAILED_CODE,
                SPACE_PROTECTION_FAILED_CODE,
            ],
            &[
                SEARCH_INVALID_QUERY_CODE,
                SEARCH_BAD_REQUEST_CODE,
                SEARCH_SESSION_LOCKED_CODE,
                SEARCH_INDEX_NOT_READY_CODE,
                SEARCH_INDEX_REBUILDING_CODE,
                SEARCH_INDEX_UNAVAILABLE_CODE,
                SEARCH_SERVICE_UNAVAILABLE_CODE,
                SEARCH_REBUILD_ALREADY_RUNNING_CODE,
                SEARCH_FAILED_CODE,
            ],
            &[
                QUERY_DIAGNOSTICS_FAILED_CODE,
                UPDATE_DEBUG_MODE_FAILED_CODE,
                EXPORT_DIAGNOSTIC_LOGS_FAILED_CODE,
                EXPORT_DIAGNOSTIC_LOGS_INVALID_TARGET_CODE,
                EXPORT_DIAGNOSTIC_LOGS_UNAUTHORIZED_CODE,
                EXPORT_DIAGNOSTIC_LOGS_UNAVAILABLE_CODE,
            ],
            &[
                RECEIVE_INVALID_INPUT_CODE,
                RECEIVE_UNAVAILABLE_CODE,
                RECEIVE_FAILED_CODE,
                TRANSFER_CANCEL_UNAVAILABLE_CODE,
                TRANSFER_CANCEL_FAILED_CODE,
            ],
            &[
                EXPORT_CONFIG_FAILED_CODE,
                PREVIEW_CONFIG_IMPORT_FAILED_CODE,
                STAGE_CONFIG_IMPORT_FAILED_CODE,
                CONFIG_FILE_INVALID_HANDLE_CODE,
                CONFIG_FILE_UNAUTHORIZED_CODE,
                CONFIG_FILE_UNAVAILABLE_CODE,
            ],
            &[
                LIST_MOBILE_DEVICES_FAILED_CODE,
                REVOKE_MOBILE_DEVICE_FAILED_CODE,
                AUTHENTICATE_MOBILE_REQUEST_FAILED_CODE,
                REVALIDATE_MOBILE_CREDENTIAL_FAILED_CODE,
                REGISTER_MOBILE_DEVICE_FAILED_CODE,
                UPDATE_MOBILE_DEVICE_FAILED_CODE,
                QUERY_MOBILE_SYNC_SETTINGS_FAILED_CODE,
                UPDATE_MOBILE_SYNC_SETTINGS_FAILED_CODE,
            ],
        ] {
            assert_unique(codes);
        }
    }
}
