[package]
name = "uc-connectivity-host"
version.workspace = true
edition = "2021"
license.workspace = true
publish = false

[features]
default = ["current-engine"]
current-engine = []

[dependencies]
anyhow = "1"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
uc-engine = { path = "../../../crates/uc-engine", features = ["dev-tools"] }

[lints]
workspace = true
